=== mergeorge/wardrobe-makeover/service.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="service">
	<xs:complexType>
	    <xs:sequence>
	        <xs:element name="booking" maxOccurs="unbounded">
	        	<xs:complexType>
				    <xs:sequence>
						<xs:element name="id" type="xs:integer"/>
						<xs:element name="category" type="xs:string"/>
				        <xs:element name="size" type="xs:string"/>
				        <xs:element name="brand" type="xs:string"/>
				        <xs:element name="instock" type="xs:string"/>
						<xs:element name="contact" type="ty"/>
            			
				    </xs:sequence>
				</xs:complexType>
	        </xs:element>
	    </xs:sequence>
	</xs:complexType>
</xs:element>
<xs:simpleType name="ty">
<xs:restriction base="xs:integer">
<xs:minExclusive value="999999999"></xs:minExclusive>
<xs:maxExclusive value="10000000000"></xs:maxExclusive>
</xs:restriction>
</xs:simpleType>
</xs:schema>

=== mergeorge/wardrobe-makeover/service.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="service.xsl"?>
<service xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="service.xsd"> 
	
	<booking>
		<id>1256513</id>
		<category>Stoles</category>
		<size>S-M</size>
		<brand>Zara</brand>
		<instock>Yes</instock>
		<contact>2020-08-20</contact>
		

	</booking>
<booking>
		<id>1257845</id>
		<category>Skirts</category>
		<size>S-L</size>
		<brand>Gucci</brand>
		<instock>Yes</instock>
		<contact>2020-08-20</contact>

	</booking>
	<booking>
		<id>1256534</id>
		<category>Shrugs</category>
		<size>S-L</size>
		<brand>Code</brand>
		<instock>Yes</instock>
		<contact>2020-08-998</contact>

	</booking>
	<booking>
		<id>1256513</id>
		<category>Jackets</category>
		<size>S-XL</size>
		<brand>In-Store</brand>
		<instock>Yes</instock>
		<contact>2020-08-20</contact>

	</booking>
	
</service>
